import re
from typing import Type, TypeVar, Optional, List, Dict, Any
from pydantic import BaseModel
from app.ai.base import AIProvider, AIProviderError

T = TypeVar("T", bound=BaseModel)

class MockAIProvider(AIProvider):
    """Deterministic, zero-latency, offline AI provider for testing and reliable demos."""

    async def extract_structured(
        self,
        prompt: str,
        schema: Type[T],
        system_instruction: Optional[str] = None,
    ) -> T:
        schema_name = schema.__name__
        if schema_name == "RawResumeExtraction":
            return self._extract_resume_claims(prompt, schema)
        elif schema_name == "RawJobExtraction":
            return self._extract_job_claims(prompt, schema)
        else:
            try:
                return schema()
            except Exception as e:
                raise AIProviderError(f"Mock provider cannot construct schema '{schema_name}': {str(e)}") from e

    async def generate_text(
        self,
        prompt: str,
        system_instruction: Optional[str] = None,
    ) -> str:
        return "Deterministic explanation generated by MockAIProvider."

    def _extract_resume_claims(self, text: str, schema: Type[T]) -> T:
        if "--- RESUME TEXT START ---" in text:
            text = text.split("--- RESUME TEXT START ---")[1].split("--- RESUME TEXT END ---")[0].strip()

        lines = [line.strip() for line in text.splitlines() if line.strip()]
        name = lines[0] if lines else "Candidate"
        
        email_match = re.search(r'[\w\.-]+@[\w\.-]+\.\w+', text)
        email = email_match.group(0) if email_match else None
        
        phone_match = re.search(r'(\+?\d{1,3}[\s-]?)?\(?\d{3}\)?[\s-]?\d{3}[\s-]?\d{4}', text)
        phone = phone_match.group(0) if phone_match else None

        education_list = []
        edu_keywords = ["b.tech", "b.e.", "bca", "mca", "m.tech", "bachelor", "master", "diploma"]
        year_pattern = r'\b(201\d|202\d|2030)\b'
        
        for line in lines:
            line_lower = line.lower()
            if any(kw in line_lower for kw in edu_keywords):
                degree = None
                if "b.tech" in line_lower or "bachelor of technology" in line_lower:
                    degree = "B.Tech"
                elif "b.e." in line_lower or "bachelor of engineering" in line_lower:
                    degree = "B.E."
                elif "mca" in line_lower:
                    degree = "MCA"
                elif "m.tech" in line_lower:
                    degree = "M.Tech"
                else:
                    degree = "Bachelor's"

                branch = None
                if "computer science" in line_lower or "cse" in line_lower:
                    branch = "Computer Science and Engineering"
                elif "information technology" in line_lower or "it" in line_lower:
                    branch = "Information Technology"
                elif "data science" in line_lower or "ai" in line_lower:
                    branch = "AI & Data Science"
                elif "mechanical" in line_lower:
                    branch = "Mechanical Engineering"

                years = re.findall(year_pattern, line)
                grad_year = int(years[-1]) if years else None

                institution = None
                for inst_kw in ["coep", "university", "institute", "college", "vjti", "pune", "mumbai"]:
                    if inst_kw in line_lower:
                        institution = line
                        break

                education_list.append({
                    "degree": degree,
                    "branch": branch,
                    "institution": institution,
                    "graduation_year": grad_year,
                    "student_status": "final_year" if grad_year and grad_year >= 2025 else "recent_graduate",
                    "source_context": line[:120]
                })

        known_skill_tokens = [
            ("cpp", ["c++", "cpp", "c plus plus"]),
            ("python", ["python", "python3", "py"]),
            ("java", ["java", "core java", "java 8", "java 11", "java 17", "java 21"]),
            ("javascript", ["javascript", "js", "es6"]),
            ("typescript", ["typescript", "ts"]),
            ("sql", ["sql", "ansi sql", "queries"]),
            ("postgresql", ["postgresql", "postgres", "pgsql"]),
            ("mysql", ["mysql"]),
            ("mongodb", ["mongodb", "mongo"]),
            ("redis", ["redis"]),
            ("fastapi", ["fastapi", "fast api"]),
            ("spring-boot", ["spring boot", "springboot", "spring-boot", "spring"]),
            ("react", ["react", "react.js", "reactjs"]),
            ("nextjs", ["next.js", "nextjs"]),
            ("html-css", ["html", "css", "html5", "css3"]),
            ("dsa", ["data structures", "algorithms", "dsa", "leetcode"]),
            ("oop", ["object-oriented", "oop", "oops", "object oriented"]),
            ("dbms", ["dbms", "database management"]),
            ("operating-systems", ["operating systems", "os", "linux"]),
            ("computer-networks", ["computer networks", "networking", "tcp/ip"]),
            ("rest-apis", ["rest", "restful", "rest api", "api"]),
            ("system-design", ["system design", "microservices", "hld", "lld"]),
            ("git", ["git", "github", "version control"]),
            ("docker", ["docker", "containerization", "containers"]),
            ("testing", ["testing", "unit testing", "pytest", "junit"]),
            ("machine-learning", ["machine learning", "ml"]),
            ("pytorch", ["pytorch", "torch"]),
            ("tensorflow", ["tensorflow", "tf"]),
        ]

        text_lower = text.lower()
        extracted_skills = []
        seen_skills = set()

        for canonical_hint, tokens in known_skill_tokens:
            for token in tokens:
                escaped = re.escape(token)
                pattern = r'(?<![a-zA-Z0-9_])' + escaped + r'(?![a-zA-Z0-9_])'
                match = re.search(pattern, text_lower)
                if match:
                    if canonical_hint not in seen_skills:
                        seen_skills.add(canonical_hint)
                        start = max(0, match.start() - 30)
                        end = min(len(text), match.end() + 30)
                        extracted_skills.append({
                            "raw_text": token,
                            "source_context": text[start:end].strip().replace("\n", " "),
                            "claimed_level": None,
                        })
                    break

        projects = []
        proj_matches = re.finditer(r'(?:Project|Projects|1\.|2\.)\s*[:\-\n]?\s*([^\n]+)', text, re.IGNORECASE)
        for m in proj_matches:
            title = m.group(1).strip()
            if len(title) > 5 and len(title) < 100:
                projects.append({
                    "name": title,
                    "description": title,
                    "source_context": title
                })

        payload = {
            "candidate_name": name,
            "email": email,
            "phone": phone,
            "education_claims": education_list,
            "skill_claims": extracted_skills,
            "project_claims": projects[:4],
            "experience_claims": [],
            "certification_claims": [],
            "raw_text": text,
        }
        return schema(**payload)

    def _extract_job_claims(self, text: str, schema: Type[T]) -> T:
        if "--- JOB DESCRIPTION START ---" in text:
            text = text.split("--- JOB DESCRIPTION START ---")[1].split("--- JOB DESCRIPTION END ---")[0].strip()

        lines = [line.strip() for line in text.splitlines() if line.strip()]
        
        # 1. Job Title & Company
        title = lines[0] if lines else "Software Engineer"
        company = "Target Company"
        
        for line in lines:
            if "company:" in line.lower() or "at " in line.lower():
                company = line.replace("Company:", "").strip()
                break

        # Target Role mapping
        text_lower = text.lower()
        if "full stack" in text_lower or "fullstack" in text_lower:
            target_role = "Full Stack Engineer"
        elif "backend" in text_lower:
            target_role = "Backend Engineer"
        elif "ai" in text_lower or "machine learning" in text_lower or "ml" in text_lower:
            target_role = "AI/ML Engineer"
        elif "data engineer" in text_lower or "data engineering" in text_lower:
            target_role = "Data Engineer"
        else:
            target_role = "Software Engineer"

        # 2. Eligibility Requirements
        eligibility = []
        # Degree
        if any(kw in text_lower for kw in ["bachelor", "b.tech", "b.e.", "degree", "bs"]):
            eligibility.append({
                "criterion_type": "degree",
                "expected_value": ["B.Tech", "B.E.", "Bachelor's", "MCA"],
                "operator": "IN",
                "is_mandatory": True,
                "supporting_text": "Bachelor's degree or equivalent technical degree required."
            })
        # Branch
        if any(kw in text_lower for kw in ["computer science", "cs", "it", "information technology"]):
            eligibility.append({
                "criterion_type": "branch",
                "expected_value": ["Computer Science", "Information Technology"],
                "operator": "IN",
                "is_mandatory": True,
                "supporting_text": "Discipline in Computer Science, IT or related engineering branch."
            })
        # Experience
        exp_match = re.search(r'(\d+)\s*[-–to]+\s*(\d+)\s*years?', text_lower)
        if exp_match:
            min_exp = int(exp_match.group(1))
            eligibility.append({
                "criterion_type": "min_experience_years",
                "expected_value": min_exp,
                "operator": "GREATER_EQUAL",
                "is_mandatory": True,
                "supporting_text": f"Experience requirement: {exp_match.group(0)}."
            })

        # Location
        if "pune" in text_lower:
            loc_city = "Pune"
        elif "mumbai" in text_lower:
            loc_city = "Mumbai"
        else:
            loc_city = "Pune"

        # 3. Competency Requirements
        known_skill_tokens = [
            ("java", ["java", "core java"]),
            ("spring-boot", ["spring boot", "springboot", "spring"]),
            ("python", ["python", "python3"]),
            ("fastapi", ["fastapi", "fast api"]),
            ("cpp", ["c++", "cpp"]),
            ("sql", ["sql", "ansi sql", "queries"]),
            ("postgresql", ["postgresql", "postgres", "pgsql"]),
            ("mysql", ["mysql"]),
            ("mongodb", ["mongodb", "mongo"]),
            ("redis", ["redis"]),
            ("docker", ["docker", "containers"]),
            ("aws", ["aws", "amazon web services"]),
            ("git", ["git", "github"]),
            ("dsa", ["data structures", "algorithms", "dsa"]),
            ("oop", ["object-oriented", "oop", "oops"]),
            ("rest-apis", ["rest", "restful", "rest api", "apis"]),
            ("testing", ["testing", "unit testing", "pytest", "junit"]),
            ("system-design", ["system design", "microservices"]),
        ]

        competencies = []
        seen_skills = set()

        for canonical_hint, tokens in known_skill_tokens:
            for token in tokens:
                escaped = re.escape(token)
                pattern = r'(?<![a-zA-Z0-9_])' + escaped + r'(?![a-zA-Z0-9_])'
                match = re.search(pattern, text_lower)
                if match:
                    if canonical_hint not in seen_skills:
                        seen_skills.add(canonical_hint)
                        start = max(0, match.start() - 40)
                        end = min(len(text), match.end() + 40)
                        context = text[start:end].strip().replace("\n", " ")
                        
                        # Determine if preferred or required
                        context_lower = context.lower()
                        is_pref = any(pw in context_lower for pw in ["prefer", "preferred", "nice to have", "plus", "optional", "familiarity"])
                        
                        competencies.append({
                            "raw_skill_text": token,
                            "is_required": not is_pref,
                            "importance_level": "preferred" if is_pref else "required",
                            "interview_relevance": "high" if canonical_hint in ["dsa", "java", "cpp", "python", "system-design"] else "medium",
                            "supporting_text": context,
                            "is_explicit": True,
                            "provenance": "extracted_from_jd"
                        })
                    break

        payload = {
            "job_title": title,
            "company_name": company,
            "target_role": target_role,
            "location_city": loc_city,
            "location_state": "Maharashtra",
            "employment_type": "Full-time",
            "eligibility_requirements": eligibility,
            "competency_requirements": competencies,
            "raw_description": text,
        }
        return schema(**payload)
